version: 2
jobs:
  build: 
    docker:
      - image: golang:latest
    working_directory: /go/src/alaija/rock_n_walk_bot

    steps: # steps that comprise the `build` job
      - checkout # check out source code to working directory

      - run: go get -d -v ./...
      - run: go install -v ./...